---
# tasks file for lab.nfs-ganesha

- name: create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ gfs_vol }}"
    bricks: "{{ gfs_bricks }}"
    rebalance: yes
    cluster: "{{ gfs_cluster }}"
    start_on_create: yes
    force: yes

- name: check the mounting
  shell: df -hTP "{{ gfs_part }}" 
  register: mnt_out
- name: mounting result
  debug:
    var: mnt_out
- name: disable nfs feature in Glusterfs
  shell: gluster volume set "{{ gfs_vol }}" nfs.disable on

- name: Install NFS-Ganesha GlusterFS Cluster.
  dnf: 
    enablerepo: extras
    name: centos-release-nfs-ganesha30
    state: present

- name: install nfs-ganesha packages
  dnf:
    enablerepo: centos-nfs-ganesha3
    name: nfs-ganesha-gluster
    state: present
- name: adding nfs-ganesha configuration
  template:
    src: ganesha.conf.j2
    dest: /etc/ganesha/ganesha.conf
  notify: start_ganesha
- name: enable nfs on firewall
  firewalld:
    service: nfs
    state: enabled
    permanent: yes
    immediate: yes
