---
# vars file for lab.hardening-sys
user: vagrant
skel_dir_files:
  - skel/.bashrc
  - skel/.bash_profile
  - skel/.bash_logout
packages:
  - vim
  - bash-completion
  - bind-utils
  - net-tools
update: true
dns_master_ip: 192.168.2.2
dns_slave_ip: 192.168.2.3
