---
- name: Ensure necessary packages are installed
  package:
    name: "{{ item }}"
  loop: "{{ vpn_packages }}"
- name: make a dir to sotre logs for openvpn
  file:
    path: "{{ item }}"
    state: directory
  loop: 
    - /var/log/openvpn
    - /etc/openvpn/easy-rsa
- name: setting the configuration file
  copy:
    src: easy-rsa.tar.xz
    dest: /etc/openvpn/easy-rsa
- name: extract the easy-rsa.tar.xz file
  unarchive:
    remote_src: yes
    src: /etc/openvpn/easy-rsa/easy-rsa.tar.xz
    dest: /etc/openvpn/easy-rsa
- name: delete the tar file
  file:
    path: /etc/openvpn/easy-rsa/easy-rsa.tar.xz
    state: absent
    
    # use ../files/install-vpn-server.sh
#- name: Generate the master Certificate Authority (CA) 
- name: OpenVPN Server Configuration
  template:
    src: server.conf
    dest: /etc/openvpn
- name: enable the kernel module
  shell: modprobe tun
- name: start the openvpn service
  service:
    name: openvpn
    state: started
    enabled: yes
#- name: checking 
  #shell: ifconfig tun
  #register: ifconfig_result
#- name: showing the result
  #debug:
    #var: ifconfig_result
#- name: netstat 
  #shell: netstat -nlup
  #register: netstat_result
#- name: showing the result
  #debug:
    #var: netstat_result
...
