# tasks file for lab.hardening-sys
---
- name: adding multiple conf files for system hardening
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "hardening.conf.j2", dest: "/etc/modprobe.d/hardening.conf", owner: "root", group: "root", mode: "0640"} #ogm
    - { src: "usb-auth.sh", dest: "/opt/usb-auth.sh", owner: "root", group: "root", mode: "0700"} #og
    - { src: "usb-auth.service", dest: "/etc/systemd/system/usb-auth.service", owner: "root", group: "root", mode: "0700"} # og
    - { src: "sysctl.conf.j2", dest: "/etc/sysctl.conf", owner: "root", group: "root", mode: "0700"} # og
    - { src: "limits.conf.j2", dest: "/etc/security/limits.conf", owner: "root", group: "root", mode: "0700"} # og
    - { src: "unowned_files", dest: "/etc/cron.daily/unowned_files", owner: "root", group: "root", mode: "0700"}
  notify: 
    - start usb-auth-service
    - load sysctl settings
- name: ensure that all files are owner by a user
  shell: find / -ignore_readdir_race -nouser -print -exec chown root {} \;
  register: file_owned_by_user
- debug:
    var: file_owned_by_user
- name: Monitor SUID/GUID Files
  shell: find / -xdev -type f -perm -4000 -o -perm -2000
  register: suid_guid
- debug:
    var: suid_guid
