---
# tasks file for lab.glusterfs
- name: create a partition
  parted:
    device: "{{ gfs_dev }}"
    number: 1
    state: present
  register: dev_info
- debug:
    var: dev_info

- name: Create an {{gfs_fstype }} filesystem on {{ gfs_dev }}
  filesystem:
    fstype: "{{ gfs_fstype }}"
    dev: "{{ gfs_part }}"

- name: Enabling the needed repos
  shell: dnf config-manager --enable extras appstream baseos

- name: create the glusterfs repo
  package:
    name: "{{ gfs_repo}}"

- name: Enabling the PowerTools repo
  shell: dnf config-manager --set-enabled powertools

- name: installing glusterfs needed packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ gfs_packages }}"

- name: Start and enable the {{ gfs_service }} service
  service:
    name: "{{ gfs_service }}"
    state: started
    enabled: yes

- name: Allow GlusterFS on Firewall
  firewalld:
    service: "{{ gfs_firewall_service }}"
    state: enabled
    permanent: yes
  notify: reload_firewalld

- name: delete the volume directory
  file:
    path: "{{ gfs_bricks }}"
    state: absent
  failed_when: false

- name: create the volume directory
  file:
    path: "{{ gfs_bricks }}"
    state: directory
    recurse: yes
