---
# tasks file for esiedge.master-dhcp-server
- name: install essential packages
  package:
    name: "{{ dhcp_package }}"
    state: present
################
#    REVISIT
################
- name: enable dhcp service on firewalld
  firewalld:
    service: "{{ dhcp_firewall_service }}"
    state: enabled
    permanent: yes
- name: setting up DHCPD configuration file 
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: 0600
    
- name: start and enable {{ dhcp_service }} service 
  service: 
    name: "{{ dhcp_service }}"
    state: started
    enabled: yes

