---
# tasks file for lab.dhcp-server

- name: install the dhcp package
  package:
          name: "{{ dhcp_package }}"
          state: present

#- name: start and enable the dhcp service
#  service:
#   name: {{ dhcp_service }}
#    state: started
#    enabled: yes  

- name: configuring the dhcp server
  template:
          src: templates/dhcpd.conf.j2
          dest: /etc/dhcp/dhcpd.conf
  notify: restart the dhcp service


- name: alow the dhcp service on the firewall
  firewalld:
          service: dhcp
          state: enabled
          permanent: yes
          immediate: yes
  notify: reload_firewalld        


