---
# handlers file for esiedge.nfs-ganesha
- name: start_ganesha
  service:
    name: nfs-ganesha
    state: started

- name: restart_net
  service:
    name: NetworkManager
    state: restarted

- name: reload_firewalld
  shell: firewall-cmd --reload
