user: vagrant
target: all
hostname: dhcp-dns.esiedge.local
dhcp_package: dhcp-server
dhcp_service: dhcpd
firewalld_dhcp_service: dhcp

dns_package: unbound
dns_service: unbound
firewalld_dns_service: dns

skel_dir_files:
  - skel/.bashrc
  - skel/.bash_profile
  - skel/.bash_logout
packages:
  - vim
  - bash-completion
  - virt-install
  - syslinux
