---
- name: CentOS Configuration for RHCSA Condidate
  hosts: "{{target}}"
  user: "{{user}}"
  become: True
  # the file that contain all the variables.
  vars_files:
    - vars.yml
  tasks:
    # check if one of the traditional repo file exists
    - name: Detect Old Repos 
      stat:
        path: /etc/yum.repos.d/CentOS-Base.repo
      register: st

   # debug info 
    - debug:
        msg: "Old Repos Exist"
      when: st.stat.exists == True
    - debug:
        msg: "Old Repos does'nt Exist"
      when: st.stat.exists == false

   # First: compress the old repos --> /root/centos_old_repos.tar.gz
   # if they exist
    - name: Compress Old Repos into /root/centos_old_repos.tar.gz
      archive:
        path: /etc/yum.repos.d/*
        dest: /root/centos_old_repos.tar.gz
        format: gz
      when: st.stat.exists == true

  # Then Delete them if they exists also.
    - name: Delete Old Repos
      file:
        path: /etc/yum.repos.d/CentOS-{{item}}.repo
        state: absent
      loop:
        - Base
        - CR
        - Debuginfo
        - fasttrack
        - Media
        - Sources
        - Vault
      when: st.stat.exists == true

  # Copy the root/user bashrc templates and manage its permissions 
    - name: Copy root_bashrc template
      copy:
        src: root_bashrc
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0644

    - name: Copy user_bashrc template
      copy:
        src: user_bashrc
        dest: /home/{{user}}/.bashrc
        owner: "{{user}}"
        group: "{{user}}"
        mode: 0644

    - name: Copy the skel folder
      copy:
        src: skel
        dest: /etc/
        directory_mode: True
        owner: root
        group: root
        mode: 0644

    - name: Copy hosts file
      copy:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644

    # 3- Mount the Centos-DVD on media

    - name: Mounting CentOS-DVD on /media
      mount:
        path: /media
        src: /dev/sr0
        fstype: iso9660
        opts: ro,noauto
        state: mounted
      register: mnt_stat
      failed_when: False
      
   # 4- Create a local repo from the Centos-DVD
    - name:  Add Local YUM repo
      yum_repository:
        name: Local
        description: Local YUM repo
        baseurl: file:///media
        enabled: yes
        gpgcheck: no

    - name: Clean YUM cache
      shell: yum clean all
      changed_when: False
      when: mnt_stat.changed == True
  # 5- Install essantial packages
    - name: Install Essential packages
      package:
        name: "{{packages}}"
        state: present

  # 6- Modify the hostname
    - name: Manage hostname
      hostname:
        name: "{{hostname}}"
...
