---
- name: Configure a DHCP server
  hosts: "{{ target }}"
  user: "{{ user }}"
  become: True
  # the file that contain all the variables
  vars_files:
    - vars.yml
  tasks:
    # Installing the dhcp package
    - name: install "{{ dhcp_package }}"
      package:
        name: "{{ dhcp_package }}"
        state: present
    # starting the firewalld
    - name: start/enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    # Service config
    #- name: enable "{{ dhcp_service }}"
      #service:
        #name: "{{ dhcp_service }}"
        #state: started
        #enabled: yes
    # Firewalld
    - name: enable "{{ dhcp_service }}" on firewalld
      firewalld:
        service: "{{ firewalld_dhcp_service }}"
        state: enabled
        permanent: yes
    # configuration file
    - name: setting the dhcp configuration file
      template:
        src: ./dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: 0600
      notify: restart_dhcp
    # change the dhcpd.conf file permission
  handlers:
    - name: restart_dhcp
      service:
        name: "{{ dhcp_service }}"
        state: restarted
